name: TEST-ALLURE
on:
#  schedule:
#    - cron: '*/3 * * * *'
  workflow_dispatch:
    inputs:
      EXEC_TEST_TYPE:
        description: 'Which tests need to be executed? The options are all, python, java, batch, cli, standalone-cli and apiserver'
        required: true
        default: 'all'
jobs:
  run_test:
    runs-on: ubuntu-latest
#    container:
#      image: ghcr.io/4paradigm/centos6_gcc7_fesql:0.0.1-legacy
#      credentials:
#        username: ${{ github.actor }}
#        password: ${{ secrets.CR_PAT_ZW }}
    steps:
      - uses: actions/checkout@v1
      - run: echo "branch:$GITHUB_REF"
      - name: run_test
        run: mvn clean test
      - name: tar test report
        if: ${{ failure() }}
        run: tar -zcvf allure-results.tar.gz target/allure-results
#      - name: Get Allure history
#        uses: actions/checkout@v2
#        if: always()
#        continue-on-error: true
#        with:
#          ref: gh-pages
#          path: gh-pages
#      - name: allure-report
#        uses: simple-elf/allure-report-action@master
#        if: always()
#        id: allure-report
#        with:
#          allure_results: target/allure-results
##          gh_pages: gh-pages
##          allure_report: allure-report
#          allure_history: allure-history
#      - name: Deploy report to Github Pages
#        if: always()
#        uses: peaceiris/actions-gh-pages@v2
#        env:
#          PERSONAL_TOKEN: ${{ secrets.CR_PAT_ZW }}
#          PUBLISH_BRANCH: gh-pages
#          PUBLISH_DIR: allure-history
      - name: 'Send mail'
        if: ${{ failure() }}
        uses: dawidd6/action-send-mail@master
        with:
          server_address: smtp.partner.outlook.cn
          server_port: 587
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: test Report
          body: ok
          to: zw1020688@163.com
          from: GitHub Actions
          content_type: text/plain
          attachments: allure-results.tar.gz

#      - name: 'Send mail'
#        if: always()
#        uses: dawidd6/action-send-mail@master
#        with:
#          server_address: smtp.163.com
#          server_port: 25
#          username: ${{ secrets.MAIL_USERNAME }}
#          password: ${{ secrets.MAIL_PASSWORD }}
#          subject: test Report
#          body: ok
#          to: zhaowei01@4paradigm.com
#          from: GitHub Actions
#          content_type: text/plain



